---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xxw.
--- DateTime: 2019/9/3 22:58
---

--print(package.path)

--function max(a)
--    local m = 1
--    local mi = a[m]
--    for i, v in ipairs(a) do
--        if v > mi
--        then
--            mi = v
--            m = i
--        end
--    end
--    return m, mi
--end
--
--print(max({ 1, 3, 4, 5, 6, 22, 12, 0, 11 }))

--a="hello"
--print(string.reverse(a))
--print(string.rep(a, 2))

--function square(iteratorMaxCount,currentNumber)
--    if currentNumber<iteratorMaxCount
--    then
--        currentNumber = currentNumber+1
--        return currentNumber, currentNumber*currentNumber
--    end
--end
--
--for i,n in square,3,0
--do
--    print(i,n)
--end

--array = {"Google", "Runoob"}
--
--function elementIterator (collection)
--    local index = 0
--    local count = #collection
--    -- 闭包函数
--    return function ()
--        index = index + 1
--        if index <= count
--        then
--            --  返回迭代器的当前元素
--            return collection[index]
--        end
--    end
--end
--
--for element in elementIterator(array)
--do
--    print(element)
--end

require("module")
print(module.constant)
module.func3()
print(package.path)